apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kw9wsd0x4-java-springboot
  janus-idp.io/tekton: kw9wsd0x4-java-springboot
  backstage.io/kubernetes-id: kw9wsd0x4-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kw9wsd0x4-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
